import { Metadata } from "next"
import {Trips} from "./components/Trips"

export const metadata: Metadata = {
  title: 'about',
  description: 'Generated by create next app',
}

export default function About() {
  return (
    <h1>
      <Trips />
    </h1>
  )
}